export const Questions = [
  {
    prompt: "What's the biggest animal in the world?",
    optionA: "Elephant",
    optionB: "Blue Whale",
    optionC: "Collosal Squid",
    optionD: "Giraffe",
    asnwer: "optionB",
  },
   {
    prompt: "What is the capital of Iceland?",
    optionA: "Vatnajokull",
    optionB: "Snaefellsjokull",
    optionC: "Reykavik",
    optionD: "Oxarafoss",
    asnwer: "optionC",
  },
 {
    prompt: "Who won FIFA World CUp 2018?",
    optionA: "Germany",
    optionB: "France",
    optionC: "Belgium",
    optionD: "Brazil",
    asnwer: "optionB",
  },
  {
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    asnwer: "optionC",
  },
  {
    prompt: "Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
];
